services:
  iot_server:
    image: iot_server
    build:
      args:
        - target=dev
    environment:
      ENV: dev
      PORT: 8080
    volumes:
      - .:/app
    ports:
      - "18000:8080"
    networks:
      - iot_network
    depends_on:
      - homeassistant

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./HomeAssistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    networks:
      - iot_network

networks:
  iot_network:
    driver: bridge