services:
  iot_server:
    image: iot_server
    build:
      args:
        - target=dev
    environment:
      ENV: dev
      PORT: 8080
    volumes:
      - .:/app
    ports:
      - "18000:8080"
  # homeassistant:
  #   container_name: homeassistant
  #   image: "ghcr.io/home-assistant/home-assistant:stable"
  #   volumes:
  #     - /PATH_TO_YOUR_CONFIG:/config
  #     - /etc/localtime:/etc/localtime:ro
  #     - /run/dbus:/run/dbus:ro
  #   restart: unless-stopped
  #   privileged: true
  #   network_mode: host