services:
  iot_server:
    image: iot_server
    build:
      args:
        - target=dev
    environment:
      ENV: dev
      PORT: 8080
      HOME_HOST: homeassistant
      HOME_PORT: 8123
      HA_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzYjZkNTc3N2ZkMDU0NjUzOWY1NGQwNTRmMzA4NzEzYiIsImlhdCI6MTc0OTQwNDQ0MSwiZXhwIjoyMDY0NzY0NDQxfQ._eWMA5NifMhKiD_iqMy_wpEYCBu21GjHlt4B44Wr7c0
    volumes:
      - .:/app
    ports:
      - "18000:8080"
    depends_on:
      - homeassistant
    networks:
      - iot_network

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./HomeAssistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    expose:
      - "8123"
    networks:
      - iot_network

networks:
  iot_network: