name: Raspberry Pi CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: pull code on raspberrypi
        uses: appleboy/ssh-action@1.2.2
        with:
          host: ${{ secrets.RASPBERRYPI_HOST }}
          username: ${{ secrets.RASPBERRYPI_USERNAME }}
          key: ${{ secrets.RASPBERRYPI_KEY }}
          port: 22
          script: |
            cd ~/iot_server
            git pull origin main
            docker compose restart