name: Raspberry Pi CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pull code on raspberrypi
        run:  git pull origin main

      - name: re-build docker image
        run: docker compose restart